-- example script demonstrating HTTP pipelining

init = function(args)
   local r = {}
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   table.insert( r, wrk.format(nil, "/") )
   req = table.concat(r)
end

request = function()
   return req
end
